"""empty message

Revision ID: 03801c606483
Revises: 94c3325c82a5
Create Date: 2024-08-26 10:33:40.111965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03801c606483'
down_revision = '94c3325c82a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house')
    # ### end Alembic commands ###
