"""empty message

Revision ID: 1358cfaf47a0
Revises: b5763c7abe6f
Create Date: 2024-09-13 01:25:14.760039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1358cfaf47a0'
down_revision = 'b5763c7abe6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint('house_city_key', type_='unique')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('house_city_key', ['city'])

    # ### end Alembic commands ###
