"""empty message

Revision ID: 1fe0575991c2
Revises: df48db7be64a
Create Date: 2024-09-02 09:50:03.813612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe0575991c2'
down_revision = 'df48db7be64a'
branch_labels = None
depends_on = None


def upgrade():
    traveler_role =  sa.Enum('ADMIN', 'TRAVELER', name='traveler_role')
    traveler_role.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'TRAVELER', name='traveler_role'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
