"""empty message

Revision ID: 49f38f021fe4
Revises: 1fe0575991c2
Create Date: 2024-09-04 08:30:40.891244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f38f021fe4'
down_revision = '1fe0575991c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nightly_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('nightly_rate')

    # ### end Alembic commands ###
