"""empty message

Revision ID: 5820517e5fa4
Revises: 03801c606483
Create Date: 2024-08-26 10:39:49.710613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5820517e5fa4'
down_revision = '03801c606483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
