"""empty message

Revision ID: 6b03d919f70a
Revises: 0dbee06415b7
Create Date: 2024-09-10 11:20:31.107219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b03d919f70a'
down_revision = '0dbee06415b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['longitude'])
        batch_op.create_unique_constraint(None, ['latitude'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traveler_userName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('house_name', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['traveler_userName'])
        batch_op.drop_constraint('reservations_house_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reservations_traveler_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'house', ['house_name'], ['name'])
        batch_op.create_foreign_key(None, 'traveler', ['traveler_userName'], ['userName'])
        batch_op.drop_column('house_id')
        batch_op.drop_column('traveler_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traveler_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservations_traveler_id_fkey', 'traveler', ['traveler_id'], ['id'])
        batch_op.create_foreign_key('reservations_house_id_fkey', 'house', ['house_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('house_name')
        batch_op.drop_column('traveler_userName')

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
