"""empty message

Revision ID: 6b3d5c7b8f5b
Revises: 3f6a08f4c34f
Create Date: 2024-09-19 09:42:19.055015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3d5c7b8f5b'
down_revision = '3f6a08f4c34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint('house_city_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.create_unique_constraint('house_city_key', ['city'])

    # ### end Alembic commands ###
