"""empty message

Revision ID: b545df29ab6f
Revises: 49f38f021fe4
Create Date: 2024-09-08 09:15:22.790069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b545df29ab6f'
down_revision = '49f38f021fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['latitude'])
        batch_op.create_unique_constraint(None, ['longitude'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
