"""empty message

Revision ID: ef9e22ae600e
Revises: 6e5dd2128af0
Create Date: 2024-08-22 11:17:51.044810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9e22ae600e'
down_revision = '6e5dd2128af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
